[package]
name = "type-uuid"
version = "0.1.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>", "David LeGare <dlegare.1001@gmail.com>"]
edition = "2018"

[dependencies]
type-uuid-derive = { path = "../type-uuid-derive" }
amethyst = { version = "0.10.0", optional = true }
serde = "1.0"
uuid = "0.7.1"
